### Block a user
POST http://localhost:8080/rest/api/v1/blocked-users
Content-Type: application/json

{
  "userId": "user123",
  "blockedBy": "admin456",
  "blockReason": "Violation of terms of service"
}

### Unblock a user by userId
DELETE http://localhost:8080/rest/api/v1/blocked-users/user123

### Block another user
POST http://localhost:8080/rest/api/v1/blocked-users
Content-Type: application/json

{
  "userId": "user789",
  "blockedBy": "moderator001",
  "blockReason": "Spam activity detected"
}

### Unblock another user by userId
DELETE http://localhost:8080/rest/api/v1/blocked-users/user789

###

### Allow a user
POST http://localhost:8080/rest/api/v1/allowed-users
Content-Type: application/json

{
  "userId": "user456",
  "allowedBy": "admin789",
  "allowReason": "Verified premium account"
}

### Remove allowed user by userId
DELETE http://localhost:8080/rest/api/v1/allowed-users/user456

### Allow another user
POST http://localhost:8080/rest/api/v1/allowed-users
Content-Type: application/json

{
  "userId": "user999",
  "allowedBy": "support001",
  "allowReason": "Special access granted"
}

### Remove another allowed user by userId
DELETE http://localhost:8080/rest/api/v1/allowed-users/user999
