### Block a single user
POST http://localhost:8080/rest/api/v1/blocked-users
Content-Type: application/json

[
  {
    "userId": "user124",
    "createdBy": "admin456",
    "description": "Violation of terms of service"
  }
]

### Block multiple users
POST http://localhost:8080/rest/api/v1/blocked-users
Content-Type: application/json

[
  {
    "userId": "user789",
    "createdBy": "moderator001",
    "description": "Spam activity detected"
  },
  {
    "userId": "user456",
    "createdBy": "admin789",
    "description": "Harassment"
  },
  {
    "userId": "user321",
    "createdBy": "moderator001",
    "description": "Multiple violations"
  }
]

### Get all blocked users
GET http://localhost:8080/rest/api/v1/blocked-users
Content-Type: application/json


### Get all blocked users
GET http://localhost:8080/rest/api/v1/blocked-users
Content-Type: application/json

["user789", "user456", "user321"]

### Unblock a single user
POST http://localhost:8080/rest/api/v1/blocked-users/unblock
Content-Type: application/json

["user124"]

### Unblock multiple users
POST http://localhost:8080/rest/api/v1/blocked-users/unblock
Content-Type: application/json

["user789", "user456", "user321"]
