### Block a single user
POST http://localhost:8080/rest/api/v1/blocked-users
Content-Type: application/json

[
  {
    "blockedUserId": "user124",
    "blockedBy": "admin456",
    "blockReason": "Violation of terms of service"
  }
]

### Block multiple users
POST http://localhost:8080/rest/api/v1/blocked-users
Content-Type: application/json

[
  {
    "blockedUserId": "user789",
    "blockedBy": "moderator001",
    "blockReason": "Spam activity detected"
  },
  {
    "blockedUserId": "user456",
    "blockedBy": "admin789",
    "blockReason": "Harassment"
  },
  {
    "blockedUserId": "user321",
    "blockedBy": "moderator001",
    "blockReason": "Multiple violations"
  }
]

### Get all blocked users
GET http://localhost:8080/rest/api/v1/blocked-users

### Unblock a single user
POST http://localhost:8080/rest/api/v1/blocked-users/unblock
Content-Type: application/json

["user124"]

### Unblock multiple users
POST http://localhost:8080/rest/api/v1/blocked-users/unblock
Content-Type: application/json

["user789", "user456", "user321"]
