spring:
  application:
    name: blocked-users-service

  elasticsearch:
    uris: https://localhost:9200
    username: elastic
    password: 91pSayjpFj2se4AP

cache:
  blocked-users:
    enabled: true
    refresh-interval: 30000  # 30 seconds
